#!/usr/bin/env bash
# This script installs and configures Nginx web server.

# Install Nginx
apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
service nginx start
