#!/usr/bin/env bash
# This script configures Nginx to perform a 301 Moved Permanently redirection.
sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server;/a location /redirect_me {\n    return 301 https://twitter.com/jossvega103;\n}" /etc/nginx/sites-enabled/default

sudo service nginx restart
