#!/usr/bin/env bash
# Configure HAProxy on lb-01 server
# Update package lists and install HAProxy
# Configure HAProxy to distribute traffic using roundrobin
# Ensure HAProxy can be managed via an init script
# Restart HAProxy to apply the configuratio
# Make sure the server hostnames are correctly set ([STUDENT_ID]-web-01
# and [STUDENT_ID]-web-02)
# Exit with success status

sudo apt-get update

sudo apt-get install haproxy -y

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 272808-web-01 100.26.163.195:80 check
    server 272808-web-02 100.25.168.142:80 check
EOT

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo systemctl start haproxy

sudo systemctl enable haproxy
