#!/usr/bin/env bash
# Configure HAProxy on lb-01 server
# Update package lists and install HAProxy
# Configure HAProxy to distribute traffic using roundrobin
# Ensure HAProxy can be managed via an init script
# Restart HAProxy to apply the configuratio
# Make sure the server hostnames are correctly set ([STUDENT_ID]-web-01 and [STUDENT_ID]-web-02)
# If not, follow the provided tutorial to set them up
# Exit with success status

sudo apt-get update
sudo apt-get install haproxy -y

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend Randommall.tech
    timeout client  30000
    bind 0:80
    default_backend Randommall.tech_backend

backend Randommall.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 228560-web-01 54.87.655.2:80 check
    server 228560-web-02 54.89.121.20:80 check
EOT

sudo systemctl enable haproxy

sudo systemctl restart haproxy

exit 0
