#!/usr/bin/env bash
# This script displays the PID and process
# name of processes whose name contains the word "bash"

for pid in /proc/*/; do
    pid=${pid%*/}
    pid=${pid##*/}
    if [[ -f "/proc/$pid/cmdline" ]]; then
        if grep -q "bash" "/proc/$pid/cmdline"; then
            echo "$pid $(cat "/proc/$pid/cmdline" | tr -d '\0')"
        fi
    fi
done
