#!/usr/bin/env bash
# This script displays the PID and process name of
# processes containing the word "bash" in their name.
# Using the pgrep command with the '-f' option to match
# the full command line of the processes,
# and the '-a' option to display the process name along with the PID.

pgrep -a -f bash
