#!/usr/bin/env bash

# Find the process ID of 7-highlander
PID=$(pgrep -f "7-highlander")

# Kill the process
if [ -n "$PID" ]; then
  kill "$PID"
  echo "Killed 7-highlander"
else
  echo "7-highlander process not found"
fi
