#!/usr/bin/env bash
# This script tells a story based on the content of /etc/passwd

while IFS=':' read -r username _ gid _ home shell; do
  read -r _ _ _ password info <<< "$(grep "^${username}:" /etc/shadow)"
  echo "The user $username is part of the $gid gang, lives in $home
  and rides $shell. $password's place is protected by the passcode x,
  more info about the user here: $info"
done < /etc/passwd
