#!/usr/bin/env bash
# This script configures the localhost and facebook.com IP addresses.
# Check if the script is running in Docker

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
