#!/usr/bin/env bash
# This script creates an RSA key pair with specific settings.
# Generate an RSA key pair
ssh-keygen -t rsa -b 4096 -C "vagrant@ubuntu" -f school -N "betty"
echo "RSA key pair 'school' created."
