#!/usr/bin/env bash
# Configure SSH client
# Set correct permissions for the SSH configuration file
# SSH Config File
#
Host 272808-web-01
	Hostname 100.26.163.195
	User ubuntu
	PasswordAuthentication no
	IdentityFile ~/.ssh/school
